### ISSUE TITLE
project_overview_spent_time calculate the wrong value

### ISSUE THREAD

**Issue by amizhang** [mbasset/project_overview#20]
on the project overview, the spent time shows total spent time for all projects, but not on each project. 

So i change the code like:
def project_overview_spent_time(project)
    TimeEntry.visible.sum(:hours, :include => project, :conditions => project.project_condition(true))
  end

Now it's working. Pls help to correct me if there is any better solution!

Thank you!

**Comment by amizhang** [comment]
oh, how about this:

    cond = project.project_condition(true)
    TimeEntry.visible.where(cond).sum(:hours)

**Comment by mbasset** [comment]
Could you create a PR for this?

**Comment by amizhang** [comment]
Sure thing. Thank you!
